const {TENSES,coordinates,timeline,markers,sortEvents}=window.GAME_DATA;
const KEY='grammar-time-machine-v1';
const avatars=['🤖','🧑‍🚀','🧑‍🔬','👩‍🚀','🦊','🐱'];
const missions={
  coordinates:{title:'Set the Coordinates',sub:'Choose the correct verb form.',icon:'⌖',demo:'Anna _____ her room every Saturday. → cleans',total:10},
  timeline:{title:'Repair the Timeline',sub:'Put the cards in the correct order.',icon:'⟷',demo:'every day · Tom · plays · football → Tom plays football every day.',total:10},
  sort:{title:'Sort the Events',sub:'Send each event to the right time portal.',icon:'◫',demo:'yesterday → Past Simple',total:16}
};
const defaultState={profile:null,crystals:0,history:[],best:{},sound:true};
let state=load(), screen=state.profile?'home':'welcome', session=null, modal=false;
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY))}}catch{return {...defaultState}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const sample=(a,n)=>shuffle(a).slice(0,n);
function balanced(data,n){const per=Math.floor(n/4), picked=[];Object.keys(TENSES).forEach(t=>picked.push(...sample(data.filter(x=>x.tense===t),per)));return shuffle([...picked,...sample(data.filter(x=>!picked.includes(x)),n-picked.length)]).slice(0,n)}
function beep(kind='tap'){if(!state.sound)return;try{const ac=new (window.AudioContext||window.webkitAudioContext)(),o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.frequency.value=kind==='good'?660:kind==='bad'?180:330;g.gain.setValueAtTime(.04,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.14);o.start();o.stop(ac.currentTime+.15)}catch{}}
function toast(s){const el=$('#toast');el.textContent=s;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function level(c=state.crystals){if(c>=100)return {name:'Master of Time',at:100};const at=Math.floor(c/5)*5;const names={0:'Junior Inventor',5:'Chromatic Frame',10:'Control Engineer',15:'Neon Pilot',20:'Silver Traveller',25:'Machine Builder',30:'Robot Companion',40:'Timeline Mapper',50:'Golden Mechanic',60:'Portal Rider',70:'Energy Guardian',80:'Lab Commander',90:'Time Luminary',95:'Time Machine Expert'};return {name:names[at]||`Chrononaut · Level ${at/5}`,at}}
function chrome(inner,hideProfile=false){const p=state.profile;return `<main class="shell"><header class="topbar"><button class="brand" style="background:none;border:0;color:white;cursor:pointer" data-home><span class="brand-mark">⌁</span><span>GRAMMAR TIME MACHINE</span></button><div class="top-actions"><button class="icon-btn" data-sound aria-label="Toggle sound">${state.sound?'🔊':'🔇'}</button>${p&&!hideProfile?`<button class="profile-chip" data-profile><span class="avatar">${p.avatar}</span><span class="profile-copy"><strong>${esc(p.name)}</strong><span class="crystals">◆ ${state.crystals} · ${level().name}</span></span></button>`:''}</div></header>${inner}</main>${modal?profileModal():''}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(keepPosition=false){const y=keepPosition?window.scrollY:0;let body;if(screen==='welcome')body=welcome();else if(screen==='home')body=home();else if(screen==='instruction')body=instruction();else if(screen==='game')body=game();else body=results();$('#app').innerHTML=chrome(body,screen==='welcome');$('#app').dataset.ready='yes';bindGlobal();if(screen==='game')bindGame();if(keepPosition)requestAnimationFrame(()=>window.scrollTo(0,y))}
function welcome(){const chosen=state.profile?.avatar||avatars[0];return `<section class="screen"><div class="hero"><div class="eyebrow">The timeline needs you</div><h1>GRAMMAR<br><span class="gradient-text">TIME MACHINE</span></h1><p>Repair time, practise English and power up your amazing machine.</p></div><div class="machine-wrap"><div class="machine"><span class="machine-core">⌁</span></div><div class="machine-base"></div></div><form class="panel setup" id="profile-form"><h2>Create your time traveller</h2><label class="field-label" for="name">Your name</label><input class="name-input" id="name" maxlength="18" autocomplete="off" placeholder="Enter your name" value="${esc(state.profile?.name||'')}"><span class="field-label">Choose an avatar</span><div class="avatar-grid">${avatars.map(a=>`<button type="button" class="avatar-choice ${a===chosen?'selected':''}" data-avatar="${a}">${a}</button>`).join('')}</div><input type="hidden" id="avatar" value="${chosen}"><button class="btn wide">Start the Mission →</button></form></section>`}
function home(){const next=Math.ceil((state.crystals+1)/5)*5, pct=Math.min(100,(state.crystals%5)/5*100);return `<section class="screen"><div class="lab-head"><div><div class="eyebrow">Time laboratory · online</div><h1>Choose your mission</h1></div><span class="status">● Timeline stable</span></div><div class="mission-grid">${Object.entries(missions).map(([id,m],i)=>`<article class="panel mission"><span class="num">0${i+1}</span><div class="mission-icon">${m.icon}</div><h2>${m.title}</h2><p>${m.sub}</p><div class="best">${state.best[id]!=null?`Best result: ${state.best[id]}%`:'No missions completed yet'}</div><button class="btn" data-mission="${id}">Play mission →</button></article>`).join('')}</div><div class="panel upgrade-bar"><span style="font-size:30px">◆</span><div><strong>${level().name}</strong><div style="color:var(--muted);font-size:13px">${state.crystals>=100?'All upgrades unlocked':`${next-state.crystals} more crystal${next-state.crystals===1?'':'s'} to the next upgrade`}</div></div><div class="progress-track"><div class="progress-fill" style="width:${state.crystals>=100?100:pct}%"></div></div><b>${state.crystals}/100</b></div></section>`}
function instruction(){const m=missions[session.type];return `<section class="panel instruction screen"><div class="guide">${m.icon}</div><div class="eyebrow">Mission briefing</div><h1>${m.title}</h1><p>${m.sub} There is no timer. Take your time!</p><div class="demo"><b>Example</b><br>${m.demo}</div><div class="btn-row"><button class="btn secondary" data-home>Back</button><button class="btn" data-begin>Start mission →</button></div></section>`}
function start(type){session={type,index:0,score:0,answers:[],checked:false,attempt:0};if(type==='coordinates')session.items=balanced(coordinates,10);if(type==='timeline')session.items=balanced(timeline,10).sort((a,b)=>a.difficulty-b.difficulty);if(type==='sort'){session.stage=0;session.items=makeSortItems(0);session.placements={};}screen='instruction';render()}
function makeSortItems(stage){if(stage===0)return shuffle(Object.keys(TENSES).flatMap(t=>sample(markers[t],2).map((text,i)=>({id:`m_${t}_${i}_${text}`,tense:t,text}))));return shuffle(Object.keys(TENSES).flatMap(t=>sample(sortEvents.filter(x=>x.tense===t),2)))}
function game(){const m=missions[session.type], total=session.type==='sort'?16:10, done=session.type==='sort'?session.stage*8:session.index;return `<section class="game-wrap screen"><div class="game-meta"><span class="counter">${Math.min(done+1,total)} / ${total}</span><div class="progress-track"><div class="progress-fill" style="width:${done/total*100}%"></div></div><span>${m.icon} ${m.title}</span></div>${session.type==='coordinates'?coordinatesGame():session.type==='timeline'?timelineGame():sortGame()}</section>`}
function coordinatesGame(){const q=session.items[session.index];if(!session.optionOrder||session.optionOrderIndex!==session.index){session.optionOrder=shuffle(q.options);session.optionOrderIndex=session.index}return `<div class="panel question-panel"><div class="eyebrow">Lock the correct verb form</div><h2>${q.prompt}</h2><div class="answer-options">${session.optionOrder.map(o=>`<button class="option" data-option="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="feedback"></div><button class="btn" data-check disabled>Check answer</button></div>`}
function timelineGame(){const q=session.items[session.index];if(!session.order)session.order=shuffle(q.cards.map((text,i)=>({id:i,text})));if(!session.placed)session.placed=[];const bank=session.order.filter(x=>!session.placed.includes(x.id)),line=session.placed.map(id=>session.order.find(x=>x.id===id));return `<div class="panel question-panel"><div class="eyebrow">Restore the sentence · attempt ${session.attempt+1}/2</div><p class="hint">Drag cards, or tap a card and then its destination.</p><div class="timeline-drop dropzone" data-zone="line">${line.map(wordHtml).join('')}<span class="hint empty-hint">${line.length?'':'Place every card on the timeline'}</span></div><div class="word-bank dropzone" data-zone="bank">${bank.map(wordHtml).join('')}</div><div class="feedback"></div><button class="btn" data-check ${session.placed.length===q.cards.length?'':'disabled'}>Check timeline</button></div>`}
function wordHtml(x){const onLine=session.placed.includes(x.id);return `<span class="word-wrap"><button class="word" draggable="true" data-word="${x.id}" title="${onLine?'Tap to return':'Tap to add'}">${esc(x.text)}</button>${onLine?`<span class="word-controls"><button data-shift="left" data-id="${x.id}" aria-label="Move left">‹</button><button data-shift="right" data-id="${x.id}" aria-label="Move right">›</button></span>`:''}</span>`}
function sortGame(){const title=session.stage===0?'Round 1 · Time Markers':'Round 2 · Events',review=session.sortReview;const placedIds=Object.values(session.placements).flat(),bank=session.items.filter(x=>!placedIds.includes(x.id));return `<div class="panel question-panel sort-panel"><div class="eyebrow">${title} · attempt ${session.attempt+1}/2</div><p class="hint">${review?'Check the colours, then continue.':'Drag a card to a portal, or tap the card and then the portal.'}</p><div class="sort-bank dropzone" data-zone="sortbank">${bank.map(sortCard).join('')}</div><div class="portals">${Object.entries(TENSES).map(([id,name])=>`<div class="portal dropzone" data-zone="${id}"><h3>${name}</h3>${(session.placements[id]||[]).map(cid=>sortCard(session.items.find(x=>x.id===cid))).join('')}</div>`).join('')}</div><div class="feedback ${review?(review.wrong.length?'bad':'good'):''}">${review?(review.final?'The correct portals are shown in green.':review.wrong.length?`${review.wrong.length} card${review.wrong.length===1?' is':'s are'} in the wrong portal.`:'Excellent! Every card is correct.') :''}</div><button class="btn" data-check ${!review&&placedIds.length!==8?'disabled':''}>${review?'Continue →':'Check portals'}</button></div>`}
function sortCard(x){const review=session.sortReview,cls=review?(review.wrong.includes(x.id)?'wrong':'correct'):'';return `<button class="sort-card ${cls}" draggable="${review?'false':'true'}" data-card="${esc(x.id)}">${esc(x.text)}</button>`}
function results(){const m=missions[session.type],pct=Math.round(session.score/session.total*100),cr=pct===100?3:pct>=75?2:1,newBest=pct>(state.best[session.type]??-1);return `<section class="panel results screen"><div class="eyebrow">Timeline restored</div><h1>${m.title}</h1><div class="result-orb">${pct}%</div><h2>${session.score} / ${session.total} correct</h2><div class="reward">◆ +${cr} energy crystal${cr>1?'s':''}</div><p style="color:var(--muted)">${pct===100?'Perfect work, Time Master!':pct>=75?'Excellent! The machine is running smoothly.':'Good try! Every mission makes you stronger.'}${newBest?' New best result!':''}</p><div class="btn-row"><button class="btn" data-again>Play again</button><button class="btn secondary" data-home>Choose another mission</button><button class="btn secondary" data-answers>View answers</button></div><div id="answer-list"></div></section>`}
function profileModal(){return `<div class="modal-backdrop"><section class="panel modal"><div class="modal-head"><div><div class="eyebrow">Traveller profile</div><h2>${esc(state.profile.name)} ${state.profile.avatar}</h2></div><button class="close" data-close>×</button></div><p><b style="color:var(--gold)">◆ ${state.crystals} crystals</b> · ${level().name} · ${state.history.length} sessions</p><div class="btn-row" style="justify-content:flex-start"><button class="btn secondary" data-edit-name>Change name</button><button class="btn secondary" data-edit-avatar>Change avatar</button><button class="btn danger" data-reset>Reset progress</button></div><h3 style="margin-top:25px">Recent missions</h3>${state.history.length?state.history.slice(0,8).map(h=>`<div class="history-row"><span><b>${h.title}</b><br><small>${h.date}</small></span><span>${h.score}/${h.total} · ${h.pct}% · <b style="color:var(--gold)">◆${h.crystals}</b></span></div>`).join(''):'<p style="color:var(--muted)">Complete a mission to start your history.</p>'}</section></div>`}
function bindGlobal(){
  $$('[data-home]').forEach(b=>b.onclick=()=>{modal=false;screen=state.profile?'home':'welcome';session=null;render()});
  $('[data-sound]')?.addEventListener('click',()=>{state.sound=!state.sound;save();render();beep()});
  $('[data-profile]')?.addEventListener('click',()=>{modal=true;render()});
  $('[data-close]')?.addEventListener('click',()=>{modal=false;render()});
  $$('.avatar-choice').forEach(b=>b.onclick=()=>{$$('.avatar-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#avatar').value=b.dataset.avatar;beep()});
  $('#profile-form')?.addEventListener('submit',e=>{e.preventDefault();const name=$('#name').value.trim();if(!name){toast('Please enter your name.');return}state.profile={name,avatar:$('#avatar').value};save();screen='home';render()});
  $$('[data-mission]').forEach(b=>b.onclick=()=>start(b.dataset.mission));
  $('[data-begin]')?.addEventListener('click',()=>{screen='game';render()});
  $('[data-again]')?.addEventListener('click',()=>start(session.type));
  $('[data-answers]')?.addEventListener('click',showAnswers);
  $('[data-edit-name]')?.addEventListener('click',()=>{const n=prompt('Enter a new name:',state.profile.name);if(n?.trim()){state.profile.name=n.trim().slice(0,18);save();render()}});
  $('[data-edit-avatar]')?.addEventListener('click',()=>{const i=(avatars.indexOf(state.profile.avatar)+1)%avatars.length;state.profile.avatar=avatars[i];save();render();toast('Avatar changed! Click again to see the next one.')});
  $('[data-reset]')?.addEventListener('click',()=>{if(confirm('Reset all crystals, results and profile? This cannot be undone.')){localStorage.removeItem(KEY);state={...defaultState,best:{},history:[]};modal=false;screen='welcome';render()}});
}
function bindGame(){
  if(session.type==='coordinates')bindCoordinates();
  else {if(!session.sortReview)bindDnD(); $('[data-check]')?.addEventListener('click',session.type==='timeline'?checkTimeline:(session.sortReview?continueSort:checkSort))}
}
function bindCoordinates(){
  $$('.option').forEach(o=>o.onclick=()=>{if(session.checked)return;$$('.option').forEach(x=>x.classList.remove('selected'));o.classList.add('selected');session.selected=o.dataset.option;$('[data-check]').disabled=false;beep()});
  $('[data-check]').onclick=()=>{if(!session.checked)checkCoordinate();else nextQuestion()};
}
function checkCoordinate(){const q=session.items[session.index],ok=session.selected===q.answer,userSentence=q.prompt.replace('_____',session.selected);session.checked=true;if(ok)session.score++;session.answers.push({ok,type:'sentence',user:userSentence,correct:q.completedSentence});$$('.option').forEach(o=>{o.disabled=true;if(o.dataset.option===q.answer)o.classList.add('correct');else if(o.dataset.option===session.selected)o.classList.add('wrong')});const f=$('.feedback');f.className=`feedback ${ok?'good':'bad'}`;f.textContent=ok?'Coordinates locked! Great work.':`Not quite. ${q.completedSentence}`;$('[data-check]').textContent=session.index===9?'See results':'Next →';beep(ok?'good':'bad')}
function nextQuestion(){session.index++;session.checked=false;session.selected=null;session.optionOrder=null;if(session.index>=session.items.length)finish();else render()}
let selectedCard=null;
function bindDnD(){
  $$('[draggable=true]').forEach(c=>{c.addEventListener('dragstart',e=>{selectedCard=c.dataset.word??c.dataset.card;c.classList.add('dragging');e.dataTransfer.setData('text/plain',selectedCard)});c.addEventListener('dragend',()=>c.classList.remove('dragging'));c.onclick=e=>{e.stopPropagation();const id=c.dataset.word??c.dataset.card;if(session.type==='timeline'){moveCard(id,session.placed.includes(Number(id))?'bank':'line');return}selectedCard=id;$$('[draggable=true]').forEach(x=>x.classList.remove('card-selected'));c.classList.add('card-selected')}});
  $$('.dropzone').forEach(z=>{z.addEventListener('dragover',e=>{e.preventDefault();z.classList.add('dragover')});z.addEventListener('dragleave',()=>z.classList.remove('dragover'));z.addEventListener('drop',e=>{e.preventDefault();z.classList.remove('dragover');moveCard(e.dataTransfer.getData('text/plain'),z.dataset.zone)});z.onclick=e=>{if(selectedCard&&!e.target.closest('[draggable=true]'))moveCard(selectedCard,z.dataset.zone)}});
  $$('[data-shift]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=Number(b.dataset.id),i=session.placed.indexOf(id),to=b.dataset.shift==='left'?i-1:i+1;if(to<0||to>=session.placed.length)return;[session.placed[i],session.placed[to]]=[session.placed[to],session.placed[i]];beep();render(true)})
}
function moveCard(id,zone){if(session.type==='timeline'){const n=Number(id);session.placed=session.placed.filter(x=>x!==n);if(zone==='line')session.placed.push(n)}else{Object.keys(session.placements).forEach(k=>session.placements[k]=session.placements[k].filter(x=>x!==id));if(zone!=='sortbank')(session.placements[zone]??=[]).push(id)}selectedCard=null;beep();render(true)}
function checkTimeline(){const q=session.items[session.index],user=session.placed.map(id=>session.order.find(x=>x.id===id).text),userSentence=formatSentence(user),ok=user.every((x,i)=>x===q.correctOrder[i]);if(ok){if(session.attempt===0)session.score++;session.answers.push({ok:session.attempt===0,type:'sentence',user:userSentence,correct:q.answer});feedbackThenNext(true,q.answer)}else if(session.attempt===0){session.attempt=1;beep('bad');toast('Some cards are in the wrong place. Try again!');render()}else{session.answers.push({ok:false,type:'sentence',user:userSentence,correct:q.answer});feedbackThenNext(false,`Correct order: ${q.answer}`)}}
function formatSentence(parts){let s=parts.join(' ').replace(/ \?/g,'?').trim();if(!s)return 'No answer';s=s.charAt(0).toUpperCase()+s.slice(1);return /[.!?]$/.test(s)?s:s+'.'}
function feedbackThenNext(ok,msg){beep(ok?'good':'bad');const panel=$('.question-panel');panel.querySelector('.feedback').className=`feedback ${ok?'good':'bad'}`;panel.querySelector('.feedback').textContent=msg;panel.querySelectorAll('.word').forEach(x=>x.disabled=true);const b=$('[data-check]');b.textContent=session.index===9?'See results':'Next →';b.onclick=()=>{session.index++;session.attempt=0;session.order=null;session.placed=[];if(session.index>=10)finish();else render()}}
function checkSort(){const wrong=[];Object.entries(session.placements).forEach(([zone,ids])=>ids.forEach(id=>{const item=session.items.find(x=>x.id===id);if(item.tense!==zone)wrong.push(id)}));if(session.attempt===0){session.score+=8-wrong.length;session.items.forEach(x=>{const userTense=Object.keys(session.placements).find(k=>session.placements[k].includes(x.id));session.answers.push({ok:!wrong.includes(x.id),type:'sort',item:x.text,user:userTense?TENSES[userTense]:'Not sorted',correct:TENSES[x.tense]})})}session.sortReview={wrong};beep(wrong.length?'bad':'good');render()}
function continueSort(){const review=session.sortReview,wrong=review.wrong;if(review.final){session.sortReview=null;advanceSort();return}session.sortReview=null;if(wrong.length&&session.attempt===0){Object.keys(session.placements).forEach(k=>session.placements[k]=session.placements[k].filter(id=>!wrong.includes(id)));session.attempt=1;render();return}if(wrong.length){wrong.forEach(id=>{const item=session.items.find(x=>x.id===id);Object.keys(session.placements).forEach(k=>session.placements[k]=session.placements[k].filter(x=>x!==id));(session.placements[item.tense]??=[]).push(id)});session.sortReview={wrong:[],final:true};render();return}advanceSort()}
function advanceSort(){if(session.stage===0){session.stage=1;session.attempt=0;session.items=makeSortItems(1);session.placements={};render()}else finish()}
function finish(){session.total=session.type==='sort'?16:10;const pct=Math.round(session.score/session.total*100),cr=pct===100?3:pct>=75?2:1,oldLevel=level().at;state.crystals+=cr;state.best[session.type]=Math.max(state.best[session.type]||0,pct);state.history.unshift({title:missions[session.type].title,date:new Date().toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}),score:session.score,total:session.total,pct,crystals:cr});state.history=state.history.slice(0,20);save();screen='results';render();if(level().at>oldLevel)setTimeout(()=>toast(`Upgrade unlocked: ${level().name}!`),400)}
function showAnswers(){const box=$('#answer-list');if(box.innerHTML){box.innerHTML='';return}box.innerHTML=`<div class="answers"><h3>Answer review</h3>${session.answers.map((a,i)=>`<div class="answer-row ${a.ok?'':'bad'}"><b>${a.ok?'✓':'✕'} ${i+1}. ${a.type==='sort'?esc(a.item):esc(a.correct)}</b>${a.type==='sort'?`<span class="review-line"><strong>Correct portal:</strong> ${esc(a.correct)}</span>${a.ok?'':`<span class="review-line"><strong>Your portal:</strong> ${esc(a.user)}</span>`}`:a.ok?'<span class="review-line">Your complete answer is correct.</span>':`<span class="review-line"><strong>Your answer:</strong> ${esc(a.user)}</span><span class="review-line"><strong>Correct answer:</strong> ${esc(a.correct)}</span>`}</div>`).join('')}</div>`}
render();
